{
  "openapi": "3.0.3",
  "info": {
    "description": "\n# Summary\n\nThe CAMARA Know Your Customer (KYC) Tenure API allows for verification that a network subscriber has been a customer of Telstra for a specified minimum length of time so as to establish a level of trust for the associated network subscription identifier.\n\n# API functionality\n\nThe API defines one service endpoint:\n\n- `POST /check-tenure`\n\n  Takes the network subscription identifier (e.g. the mobile phone number for a mobile network subscriber) and the specified minimum tenure date to validate for the associated network subscription. This endpoint will respond with a confirmation of whether or not the network subscriber tenure is longer than the specified date timestamp, optionally supplemented with details of the subscription contract type.\n\nTo call this endpoint, the API consumer must first obtain a valid access token with the specified scope from the specified token endpoint, which is then passed to the endpoint via the `Authorization` header. For more details on access token processing, see below.\n\n## Inputs\n\nThe endpoint request body is a JSON object with the following parameters:\n- `tenureDate`: The date from which continuous tenure of the identified network subscriber is required to be confirmed. This field is always required.\n- `phoneNumber`: The network subscription identifier (i.e. the phone number of the subscriber). This field is only required if no network subscription identifier is associated with the access token.\n\n## Outputs\n\nIf successful, a JSON object is returned containing the following data:\n- `tenureDateCheck`: `true` when the identified network subscription has had valid tenure since `tenureDate`, otherwise `false`\n- `contractType`: The network subscription account type, if known. **Telstra does not currently return this field**\n\nAn example of a JSON response object is as follows:\n```\n{\n    \"tenureDateCheck\": true,\n}\n```\n\n## Errors\n\nIf the authentication token is missing, not a valid token, or is no longer valid, a `401 UNAUTHENTICATED` error is returned\n\nIf the API call contain a formatting or other error, a `400 INVALID_ARGUMENT` error is returned.\n\nIf the network subscription cannot be identified from the provided parameters (e.g. the subscription identifier is not associated with any customer of Telstra), a `404 IDENTIFIER_NOT_FOUND` error is returned.\n\nIf the API consumer has a valid access token that does not have the required scope to obtain tenure information for the specified network subscription, then a `403 PERMISSION_DENIED` error is returned.\n\n### Additional CAMARA error responses\n\nThe list of error codes in this API specification is not exhaustive. Therefore the API specification may not document some non-mandatory error statuses as indicated in `CAMARA API Design Guide`.\n\nPlease refer to the `CAMARA_common.yaml` of the Commonalities Release associated to this API version for a complete list of error responses. The applicable Commonalities Release can be identified in the `API Readiness Checklist` document associated to this API version.\n\nAs a specific rule, error `501 - NOT_IMPLEMENTED` can be only a possible error response if it is explicitly documented in the API.\n\n# Identifying the phone number from the access token\n\nThis API requires the API consumer to identify a phone number as the subject of the API as follows:\n- When the API is invoked using a two-legged access token, the subject will be identified from the optional `phoneNumber` field, which therefore MUST be provided.\n\n- When a three-legged access token is used however, this optional identifier MUST NOT be provided, as the subject will be uniquely identified from the access token. **Telstra only uses three-legged access tokens, therefore the phoneNumber field must not be provided**\n\nThis approach simplifies API usage for API consumers using a three-legged access token to invoke the API by relying on the information that is associated with the access token and was identified during the authentication process.\n\n## Error handling:\n- If the subject cannot be identified from the access token, the server will return an error with the `422 MISSING_IDENTIFIER` error code.\n\n- If the subject can be identified from the access token and the optional `phoneNumber` field is also included in the request, then the server will return an error with the `422 UNNECESSARY_IDENTIFIER` error code. This will be the case even if the same phone number is identified by these two methods, as the server is unable to make this comparison.\n\n# Authorization and authentication\n\nThe \"Camara Security and Interoperability Profile\" provides details of how an API consumer requests an access token. Please refer to Identity and Consent Management (https://github.com/camaraproject/IdentityAndConsentManagement/) for the released version of the profile.\n\nThe specific authorization flows to be used will be agreed upon during the onboarding process, happening between the API consumer and the API provider, taking into account the declared purpose for accessing the API, whilst also being subject to the prevailing legal framework dictated by local legislation.\n\nIn cases where personal data is processed by the API and users can exercise their rights through mechanisms such as opt-in and/or opt-out, the use of three-legged access tokens is mandatory. This ensures that the API remains in compliance with privacy regulations, upholding the principles of transparency and user-centric privacy-by-design.\n\n# Further info and support\n\n(FAQs will be added in a later version of the documentation)\n",
    "title": "KYC Tenure",
    "version": "0.2.0",
    "x-camara-commonalities": 0.6,
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "externalDocs": {
    "description": "Product documentation at CAMARA",
    "url": "https://github.com/camaraproject/Tenure"
  },
  "servers": [
    {
      "url": "https://prod.okapi.ogw.evolve.okapi.telstra.com/mobility/products-api/kyc/kyc-tenure/v0.2"
    }
  ],
  "tags": [
    {
      "name": "OIDC Authentication Request",
      "description": "Request authorisation grant"
    },
    {
      "name": "OIDC Access Token Request",
      "description": "Request for access token to make the API request"
    },
    {
      "name": "Check Subscriber Tenure"
    }
  ],
  "paths": {
    "/ext/ciba/auth": {
      "post": {
        "description": "Use your `client_id` and `client_secret` that you get from the Telstra Developer portal.",
        "tags": [
          "OIDC Authentication Request"
        ],
        "summary": "Get authorization request ID for your application and end-user",
        "security": [
          {}
        ],
        "operationId": "authReqId",
        "servers": [
          {
            "url": "https://prod.okapi.ogw.evolve.okapi.telstra.com/og-network-auth-prod/api/realms/network-auth/protocol/openid-connect"
          }
        ],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "type": "object",
                "properties": {
                  "client_id": {
                    "description": "Client ID generated on your Telstra Developer account",
                    "type": "string",
                    "default": "your-client-id"
                  },
                  "client_secret": {
                    "description": "Client Secret generated on your Telstra Developer account",
                    "type": "string",
                    "default": "your-client-secret"
                  },
                  "scope": {
                    "description": "OpenID scope and purpose. [Refer to Github](https://github.com/camaraproject/IdentityAndConsentManagement/blob/r3.3/documentation/CAMARA-Security-Interoperability.md#missing-openid-scope)",
                    "type": "string",
                    "default": "openid dpv:FraudPreventionAndDetection kyc-tenure:check-tenure"
                  },
                  "login_hint": {
                    "description": "A hint to the OpenID Provider regarding the end-user for whom authentication is being requested. The value must contain a phone number which identifies the end-user.",
                    "type": "string",
                    "default": "tel:+61462925583"
                  }
                },
                "required": [
                  "client_id",
                  "client_secret",
                  "scope",
                  "login_hint"
                ]
              },
              "example": {
                "client_id": "your-client-id",
                "client_secret": "your-client-secret",
                "scope": "openid dpv:FraudPreventionAndDetection kyc-tenure:check-tenure",
                "login_hint": "tel:+61462925583"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "auth_req_id": {
                      "description": "A unique identifier to identify the authentication request made by the Client.",
                      "type": "string"
                    },
                    "expires_in": {
                      "description": "Expiry time of the auth_req_id in seconds.",
                      "type": "number"
                    },
                    "interval": {
                      "description": "Minimum amount of time the Client must wait between polling requests to the token endpoint in seconds.",
                      "type": "number"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "`scope` or `login_hint` are invalid or missing"
          },
          "401": {
            "description": "Either client_id or client_secret or both are not valid."
          },
          "404": {
            "description": "The requested URI does not exist."
          },
          "503": {
            "description": "The service is currently unavailable."
          },
          "default": {
            "description": "An internal error occurred when processing the request."
          }
        }
      }
    },
    "/token": {
      "post": {
        "tags": [
          "OIDC Access Token Request"
        ],
        "summary": "Request for OAuth2 access token",
        "description": "To generate an OAuth2 access token, use your `Client ID` and `Client secret` that you get from the Telstra Developer portal. You will also need the `auth_req_id` that was received in the previous leg.",
        "security": [
          {}
        ],
        "servers": [
          {
            "url": "https://prod.okapi.ogw.evolve.okapi.telstra.com/og-network-auth-prod/api/realms/network-auth/protocol/openid-connect",
            "description": "OAuth2 server"
          }
        ],
        "operationId": "authToken",
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "type": "object",
                "properties": {
                  "client_id": {
                    "description": "Client ID generated on your Telstra Developer account",
                    "type": "string",
                    "default": "your-client-id"
                  },
                  "client_secret": {
                    "description": "Client Secret generated on your Telstra Developer account",
                    "type": "string",
                    "default": "your-client-secret"
                  },
                  "grant_type": {
                    "type": "string",
                    "default": "urn:openid:params:grant-type:ciba"
                  },
                  "auth_req_id": {
                    "type": "string",
                    "default": "your-auth-req-id"
                  }
                },
                "required": [
                  "grant_type",
                  "auth_req_id",
                  "client_id",
                  "client_secret"
                ]
              },
              "example": {
                "client_id": "your-client-id",
                "client_secret": "your-client-secret",
                "grant_type": "urn:openid:params:grant-type:ciba",
                "auth_req_id": "your-auth-req-id"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "access_token": {
                      "description": "OAuth access token",
                      "type": "string"
                    },
                    "token_type": {
                      "description": "OAuth token type",
                      "type": "string"
                    },
                    "expires_in": {
                      "description": "OAuth expiry time in seconds.",
                      "type": "string"
                    },
                    "scope": {
                      "description": "Scopes requested for during Authentication Request",
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "`grant_type` is incorrect. `grant_type` should be `urn:openid:params:grant-type:ciba`."
          },
          "401": {
            "description": "Either client_id or client_secret or both are not valid."
          },
          "404": {
            "description": "The requested URI does not exist."
          },
          "503": {
            "description": "The service is currently unavailable."
          },
          "default": {
            "description": "An internal error occurred when processing the request."
          }
        }
      }
    },
    "/check-tenure": {
      "post": {
        "tags": [
          "Check Subscriber Tenure"
        ],
        "summary": "The KYC Tenure service API",
        "description": "Verifies a specified length of tenure, based on a provided date, for a network subscriber to establish a level of trust for the network subscription identifier.\n",
        "security": [
          {
            "openId": [
              "kyc-tenure:check-tenure"
            ]
          }
        ],
        "operationId": "checkTenure",
        "parameters": [
          {
            "in": "header",
            "name": "x-correlator",
            "description": "Correlation id for the different services",
            "required": false,
            "schema": {
              "$ref": "#/components/schemas/XCorrelator"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "examples": {
                "CheckTenureRequestBodyExample": {
                  "value": {
                    "tenureDate": "2023-07-03"
                  }
                }
              },
              "schema": {
                "$ref": "#/components/schemas/Tenure"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Respond with tenure information",
            "headers": {
              "x-correlator": {
                "$ref": "#/components/headers/X-Correlator"
              }
            },
            "content": {
              "application/json": {
                "examples": {
                  "CheckTenureResponseBodyExample": {
                    "value": {
                      "tenureDateCheck": true
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/TenureInfo"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/Generic400"
          },
          "401": {
            "$ref": "#/components/responses/Generic401"
          },
          "403": {
            "$ref": "#/components/responses/Generic403"
          },
          "404": {
            "$ref": "#/components/responses/Generic404"
          },
          "422": {
            "$ref": "#/components/responses/Generic422"
          },
          "429": {
            "$ref": "#/components/responses/Generic429"
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "openId": {
        "type": "openIdConnect",
        "openIdConnectUrl": "https://example.com/.well-known/openid-configuration"
      }
    },
    "headers": {
      "X-Correlator": {
        "description": "Correlation id for the different services",
        "required": false,
        "schema": {
          "$ref": "#/components/schemas/XCorrelator"
        }
      }
    },
    "responses": {
      "Generic429": {
        "description": "Too Many Requests",
        "headers": {
          "x-correlator": {
            "$ref": "#/components/headers/X-Correlator"
          }
        },
        "content": {
          "application/json": {
            "schema": {
              "allOf": [
                {
                  "$ref": "#/components/schemas/ErrorInfo"
                },
                {
                  "type": "object",
                  "properties": {
                    "status": {
                      "enum": [
                        429
                      ]
                    },
                    "code": {
                      "enum": [
                        "TOO_MANY_REQUESTS"
                      ]
                    }
                  }
                }
              ]
            },
            "examples": {
              "GENERIC_429_TOO_MANY_REQUESTS": {
                "description": "Access to the API has been temporarily blocked due to rate or spike arrest limits being reached",
                "value": {
                  "status": 429,
                  "code": "TOO_MANY_REQUESTS",
                  "message": "Rate limit reached."
                }
              }
            }
          }
        }
      },
      "Generic400": {
        "description": "Bad Request",
        "headers": {
          "x-correlator": {
            "$ref": "#/components/headers/X-Correlator"
          }
        },
        "content": {
          "application/json": {
            "schema": {
              "allOf": [
                {
                  "$ref": "#/components/schemas/ErrorInfo"
                },
                {
                  "type": "object",
                  "properties": {
                    "status": {
                      "enum": [
                        400
                      ]
                    },
                    "code": {
                      "enum": [
                        "INVALID_ARGUMENT",
                        "OUT_OF_RANGE"
                      ]
                    }
                  }
                }
              ]
            },
            "examples": {
              "GENERIC_400_INVALID_ARGUMENT": {
                "description": "Invalid Argument. Generic Syntax Exception",
                "value": {
                  "status": 400,
                  "code": "INVALID_ARGUMENT",
                  "message": "Client specified an invalid argument, request body or query param."
                }
              },
              "GENERIC_400_OUT_OF_RANGE": {
                "description": "Out of Range. Specific Syntax Exception used when a given field has a pre-defined range or a invalid filter criteria combination is requested",
                "value": {
                  "status": 400,
                  "code": "OUT_OF_RANGE",
                  "message": "Client specified an invalid range."
                }
              }
            }
          }
        }
      },
      "Generic401": {
        "description": "Unauthorized",
        "headers": {
          "x-correlator": {
            "$ref": "#/components/headers/X-Correlator"
          }
        },
        "content": {
          "application/json": {
            "schema": {
              "allOf": [
                {
                  "$ref": "#/components/schemas/ErrorInfo"
                },
                {
                  "type": "object",
                  "properties": {
                    "status": {
                      "enum": [
                        401
                      ]
                    },
                    "code": {
                      "enum": [
                        "UNAUTHENTICATED"
                      ]
                    }
                  }
                }
              ]
            },
            "examples": {
              "GENERIC_401_UNAUTHENTICATED": {
                "description": "Request cannot be authenticated and a new authentication is required",
                "value": {
                  "status": 401,
                  "code": "UNAUTHENTICATED",
                  "message": "Request not authenticated due to missing, invalid, or expired credentials. A new authentication is required."
                }
              }
            }
          }
        }
      },
      "Generic403": {
        "description": "Forbidden",
        "headers": {
          "x-correlator": {
            "$ref": "#/components/headers/X-Correlator"
          }
        },
        "content": {
          "application/json": {
            "schema": {
              "allOf": [
                {
                  "$ref": "#/components/schemas/ErrorInfo"
                },
                {
                  "type": "object",
                  "properties": {
                    "status": {
                      "enum": [
                        403
                      ]
                    },
                    "code": {
                      "enum": [
                        "PERMISSION_DENIED"
                      ]
                    }
                  }
                }
              ]
            },
            "examples": {
              "GENERIC_403_PERMISSION_DENIED": {
                "description": "Permission denied. OAuth2 token access does not have the required scope or when the user fails operational security",
                "value": {
                  "status": 403,
                  "code": "PERMISSION_DENIED",
                  "message": "Client does not have sufficient permissions to perform this action."
                }
              }
            }
          }
        }
      },
      "Generic404": {
        "description": "Not found",
        "headers": {
          "x-correlator": {
            "$ref": "#/components/headers/X-Correlator"
          }
        },
        "content": {
          "application/json": {
            "schema": {
              "allOf": [
                {
                  "$ref": "#/components/schemas/ErrorInfo"
                },
                {
                  "type": "object",
                  "properties": {
                    "status": {
                      "enum": [
                        404
                      ]
                    },
                    "code": {
                      "enum": [
                        "IDENTIFIER_NOT_FOUND"
                      ]
                    }
                  }
                }
              ]
            },
            "examples": {
              "GENERIC_404_IDENTIFIER_NOT_FOUND": {
                "description": "The phone number is not associated with a CSP customer account",
                "value": {
                  "status": 404,
                  "code": "IDENTIFIER_NOT_FOUND",
                  "message": "The phone number provided is not associated with a customer account"
                }
              }
            }
          }
        }
      },
      "Generic422": {
        "description": "Unprocessable Content",
        "headers": {
          "x-correlator": {
            "$ref": "#/components/headers/X-Correlator"
          }
        },
        "content": {
          "application/json": {
            "schema": {
              "allOf": [
                {
                  "$ref": "#/components/schemas/ErrorInfo"
                },
                {
                  "type": "object",
                  "properties": {
                    "status": {
                      "enum": [
                        422
                      ]
                    },
                    "code": {
                      "enum": [
                        "SERVICE_NOT_APPLICABLE",
                        "MISSING_IDENTIFIER",
                        "UNNECESSARY_IDENTIFIER"
                      ]
                    }
                  }
                }
              ]
            },
            "examples": {
              "GENERIC_422_SERVICE_NOT_APPLICABLE": {
                "description": "Service is not applicable for the provided phone number",
                "value": {
                  "status": 422,
                  "code": "SERVICE_NOT_APPLICABLE",
                  "message": "The service is not applicable for the provided phone number"
                }
              },
              "GENERIC_422_MISSING_IDENTIFIER": {
                "description": "No phone number has been provided either explicitly or associated with the access token",
                "value": {
                  "status": 422,
                  "code": "MISSING_IDENTIFIER",
                  "message": "No phone number has been provided"
                }
              },
              "GENERIC_422_UNNECESSARY_IDENTIFIER": {
                "description": "An explicit phone number has been provided when one is already associated with the access token",
                "value": {
                  "status": 422,
                  "code": "UNNECESSARY_IDENTIFIER",
                  "message": "An explicit phone number has been provided when one is already associated with the access token"
                }
              }
            }
          }
        }
      }
    },
    "schemas": {
      "Tenure": {
        "description": "Specifies date from which continuous tenure of the identified mobile subscriber is required to be confirmed",
        "type": "object",
        "properties": {
          "phoneNumber": {
            "$ref": "#/components/schemas/PhoneNumber"
          },
          "tenureDate": {
            "type": "string",
            "description": "The date, in RFC 3339 / ISO 8601 compliant format \"YYYY-MM-DD\", from which continuous tenure of the identified network subscriber is required to be confirmed",
            "format": "date",
            "example": "2023-07-03"
          }
        },
        "required": [
          "tenureDate"
        ]
      },
      "PhoneNumber": {
        "description": "**Telstra only uses three-legged access tokens, therefore this field must not be provided**. A public identifier addressing a telephone subscription. In mobile networks it corresponds to the MSISDN (Mobile Station International Subscriber Directory Number). In order to be globally unique it has to be formatted in international format, according to E.164 standard, prefixed with '+'.",
        "type": "string",
        "pattern": "^\\+[1-9][0-9]{4,14}$",
        "example": "+61462925583"
      },
      "TenureInfo": {
        "properties": {
          "tenureDateCheck": {
            "description": "`true` when the identified mobile subscription has had valid tenure since `tenureDate`, otherwise `false`\n",
            "example": true,
            "type": "boolean"
          },
          "contractType": {
            "description": "**Telstra does not currently return this field**\n\nIf exists, populated with:\n- `PAYG` - prepaid (pay-as-you-go) account\n- `PAYM` - contract account\n- `Business` - Business (enterprise) account\n\nThis attribute may be omitted from the response set if the information is not available\n",
            "example": "PAYM",
            "type": "string",
            "enum": [
              "PAYG",
              "PAYM",
              "Business"
            ]
          }
        },
        "required": [
          "tenureDateCheck"
        ]
      },
      "ErrorInfo": {
        "type": "object",
        "required": [
          "status",
          "code",
          "message"
        ],
        "properties": {
          "status": {
            "type": "integer",
            "description": "HTTP response status code"
          },
          "code": {
            "type": "string",
            "description": "A human-readable code to describe the error"
          },
          "message": {
            "type": "string",
            "description": "A human-readable description of what the event represents"
          }
        }
      },
      "XCorrelator": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9-_:;.\\/<>{}]{0,256}$",
        "example": "b4333c46-49c0-4f62-80d7-f0ef930f1c46"
      }
    }
  }
}